### ISSUE TITLE
problem when I tried to train my single-class datasets

### ISSUE THREAD

**Issue by fanqiejidantang** [nightsnack/YOLObile#14]
I made my own datasets which had only single class.Then I changed csdarknet53s-panet-spp.cfg correspondingly. When I tried pruning，the initial weights were not compatible. So how can I get compatible initial weights? And I don't know how to do training or pruning with no initial weights. Should I change pruning config either?
In general, When I try to train my own single-class datasets, what should I pay attention to?
I am a new hand, sorry for the dump question.

**Comment by baisong666** [comment]
同问

**Comment by nightsnack** [comment]
For single class, cause the output dimension is different, you should change configuration file and train a new model from scrach. Please refer to Ultralitics/yolov3 for more help

**Comment by fanqiejidantang** [comment]
thanks a lot
