### ISSUE TITLE
question about the weight_pruning function in admm.py

### ISSUE THREAD

**Issue by yxt132** [nightsnack/YOLObile#4]
Hi, I saw you have several lines in admm.py at which you reshape the weight. For example, at line 212:

weight = weight.reshape(shape) 

should it be weight = weight2d.reshape(shape)  ?

**Comment by nightsnack** [comment]
Both are correct.
 In pytorch tensor ‘=’ is a shallow copy of the original tensor. so we reshape the 4dweight 'weight' to 2d 'weight2d' before, the 'weight' is also pruned and reshaped to 2d format. This is annoying in pytorch.

**Comment by yxt132** [comment]
got it. thanks for the quick reply.
