### ISSUE TITLE
Question on config_csdarknet53pan_v*.yaml and yolov4dense.pt

### ISSUE THREAD

**Issue by e96031413** [nightsnack/YOLObile#5]
Thanks for your great work,

I am wondering the meaning of the following code in yaml file, and how do you decide which Conv2d layer to prune and the number in line (e.g 0.4)
```
module_list.1.Conv2d.weight:
    0.4
```
Finally, what's the purpose of "yolov4dense.pt"(dense model)? Does it work as a pre-trained weight? What's the difference between it and yolov4.pt file that trained from other PyTorch version YOLOv4 project.

**Comment by nightsnack** [comment]
first question:
It's prune ratio. 0.4 means 40% of the total weights are pruned.
second question:
Yes. It is pretrained. And you can use ultralytics yolov3 repe to load the cfg file and train your own.

**Comment by e96031413** [comment]
@liyy201912 
Thanks for your answering.
