### ISSUE TITLE
prune ratios

### ISSUE THREAD

**Issue by yxt132** [nightsnack/YOLObile#6]
Hi, I have question about the prune ratios. How did you determine the prune ratios for different layers as specified in the configuration files such as "config_csdarknet53pan_v2.yaml"? There are so many layers and it seems infeasible to do trial and error to determine the ratios. I am sorry for the dumb question but I am relatively new in this kind of study.

**Comment by nightsnack** [comment]
Hi @yxt132 , you could send an email to me about these questions. 
Prune ratios are designed manully. For new models, you could start with using average pruning among all layers and then decrease the ratio of small weight matrix layers (eg: 64x64x3x3, 128x256x1x1), increase the prune ratios on large size weight matrix layers(eg: 2048x4096x3x3). Manully doing the experiments and searching better results, that's how I did.

**Comment by yxt132** [comment]
Cool. Thanks for the explanation. I think some useful discussions here can also help others. I will close this issue for now. Will communicate by email if I have more questions. Thanks again!
