### ISSUE TITLE
how to keep total sparse ratio in a certain number

### ISSUE THREAD

**Issue by heguoang** [nightsnack/YOLObile#9]
Thanks for your great work,I have a question, as you mentioned in another issue, the sparse ration of each layer is manually set, first set with same sparse ratio, and then changed layer by lay. But how to keep total sparse ratio same during the adjust?

**Comment by nightsnack** [comment]
I have a util function to calculate the total prune ratio.

**Comment by heguoang** [comment]
@nightsnack Thanks a lot!  May I ask which function is it

**Comment by nightsnack** [comment]
@heguoang plz check this. https://github.com/nightsnack/YOLObile/blob/master/check_compression.py
